# Generated by Django 2.2.1 on 2019-11-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191124_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='_id',
        ),
    ]
